### PR TITLE
adjust aqua and blue in the light variant

### PR DESCRIPTION
**Pull request by sainnhe**
Aqua and blue are not distinguishable enough in the light variant, I'm tring to make them more distinguishable.

### CODE REVIEW

**Comment by sainnhe** [comment]
Sorry for bothering, but I need other people's help.

What do you think of the light variant? I found that the colors are more difficult to distinguish after the adjustment, but the contrast of the original one seems to be too low.

Other light color schemes improve the distinguishability by changing the brightness of similar colors, but I think this will make the code looks untidy, I prefer to keep the brightness of all colors consistent.

What should I do? Should I keep using current one or use the original one instead?

**Comment by rsaihe** [comment]
Hmmm, I think it can be a little bit difficult to distinguish them in the light variant, but I think the original is decent enough as is. The new version seems a little bit harder to distinguish and I think the contrast looks good enough already. So, my vote is to stick to the original.

> Sorry for bothering, but I need other people's help.

And don't worry, I don't mind helping out. It's not a bother at all! 😄

**Comment by sainnhe** [comment]
Thanks for your help!

I decided to use the original color palette instead, but slightly increased the contrast of black(used in the Normal highlight group). I'm personally satisfied with this. What do you think?

**Comment by rsaihe** [comment]
Sure, I think this looks good! I'll go ahead and merge.

**Pull request merged**
