### PR TITLE
use brighter white

### PR DESCRIPTION
**Pull request by sainnhe**
The white in the dark variant is a bit dark, I want to make it a little brighter.

### CODE REVIEW

**Comment by rsaihe** [comment]
Oh, did you change your mind about it?

**Comment by sainnhe** [comment]
Yeah, it becomes too bright after adjustment. What do you think? Is it necessary to make it brighter?

**Comment by sainnhe** [comment]
Currently, this palette is far from perfect, I decided to create a new branch to test the new colors.

After the palette reaches a steady state, I'll open another PR.

**Comment by rsaihe** [comment]
Personally, I think the current white looks fine as is. I use the color scheme pretty regularly and I haven't really noticed it being too dark or anything.

**Pull request closed without merging**
